okta:
  oauth2:
    issuer: https://dev-rtcs71fqxvr68wkj.us.auth0.com/
    audience: http://localhost:8080
cors:
  allowed-methods:
    - OPTIONS
    - GET
    - PUT
    - POST
    - PATCH
    - DELETE
  allowed-headers:
    - Accept
    - Authorization
    - Content-Type
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Methods
    - Access-Control-Allow-Headers
    - Access-Control-Expose-Headers
  exposed-headers:
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Expose-Headers
    - Content-Type
    - Authorization
    - Accept
  allow-credentials: true
  allowed-origins:
    - http://localhost:4200